spring.application.name=yers3
spring.datasource.url=jdbc:postgresql://localhost:5432/yesr3
spring.datasource.username=postgres
spring.datasource.password=tmyers18
server.port=8089

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

